name: Flake8 Lint and Mypy Check

on:
  push:
    branches:
      - '**'

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          poetry install --all-groups

      - name: Run flake8
        run: |
          poetry run flake8 .

      - name: Run mypy
        run: |
          poetry run mypy .
          
